<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-27T11:21:48 IST" name="Default suite" finished-at="2020-03-27T11:21:52 IST" duration-ms="3791">
    <groups>
    </groups>
    <test started-at="2020-03-27T11:21:48 IST" name="Default test" finished-at="2020-03-27T11:21:52 IST" duration-ms="3791">
      <class name="com.baseclass.ExtentReports123">
        <test-method is-config="true" signature="startReport()[pri:0, instance:com.baseclass.ExtentReports123@a3d8174]" started-at="2020-03-27T11:21:48 IST" name="startReport" finished-at="2020-03-27T11:21:49 IST" duration-ms="1117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="demoReportfail()[pri:0, instance:com.baseclass.ExtentReports123@a3d8174]" started-at="2020-03-27T11:21:49 IST" name="demoReportfail" finished-at="2020-03-27T11:21:50 IST" duration-ms="99" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.baseclass.ExtentReports123.demoReportfail(ExtentReports123.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportfail -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.baseclass.ExtentReports123@a3d8174]" started-at="2020-03-27T11:21:50 IST" name="getResult" finished-at="2020-03-27T11:21:50 IST" duration-ms="31" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportfail status=FAILURE method=ExtentReports123.demoReportfail()[pri:0, instance:com.baseclass.ExtentReports123@a3d8174] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method signature="demoReportpass()[pri:0, instance:com.baseclass.ExtentReports123@a3d8174]" started-at="2020-03-27T11:21:50 IST" name="demoReportpass" finished-at="2020-03-27T11:21:50 IST" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportpass -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.baseclass.ExtentReports123@a3d8174]" started-at="2020-03-27T11:21:50 IST" name="getResult" finished-at="2020-03-27T11:21:50 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportpass status=SUCCESS method=ExtentReports123.demoReportpass()[pri:0, instance:com.baseclass.ExtentReports123@a3d8174] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:com.baseclass.ExtentReports123@a3d8174]" started-at="2020-03-27T11:21:50 IST" name="endReport" finished-at="2020-03-27T11:21:52 IST" duration-ms="2161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.baseclass.ExtentReports123 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
